### ISSUE TITLE
Http Client: Invalid header value detected (after update to 1.12.12)

### ISSUE THREAD

**Issue by fromYukki** [zendframework/zf1#568]
Hello guys
I noticed that we have thousands of error after updating to new version 1.12.12.

Here is my stack trace:
```
'Exception Zend_Http_Exception in /vendor/zendframework/zendframework1/library/Zend/Http/Client.php:1597
Message: Invalid header value detected
Trace: #0 /vendor/zendframework/zendframework1/library/Zend/Http/Client.php(467): Zend_Http_Client->_validateHeaderValue(39163)
#1 /vendor/zendframework/zendframework1/library/Zend/Http/Client.php(1358): Zend_Http_Client->setHeaders(''Content-Length'', 39163)
#2 /vendor/zendframework/zendframework1/library/Zend/Http/Client.php(1061): Zend_Http_Client->_prepareBody()
```
`_prepareBod`y function sets `Content-Length` header like `Integer`. But then `Validation` function reject it because it is waiting for `string` or `object` with `__toString` function.

Please fix asap!

**Comment by froschdesign** [comment]
Already done: #567
Release is coming.
