### ISSUE TITLE
Zend_Gdata_MediaMimeStream sets invalid content type in 1.12.13

### ISSUE THREAD

**Issue by rokclimb15** [zendframework/zf1#572]
PHP Fatal error:  Uncaught exception 'Zend_Http_Header_Exception_InvalidArgumentException' with message 'Invalid header value' in /usr/share/php/zend-framework-1.12.13/Zend/Http/Header/HeaderValue.php:124
Stack trace:
#0 /usr/share/php/zend-framework-1.12.13/Zend/Http/Client.php(1605): Zend_Http_Header_HeaderValue::assertValid('multipart/relat...')
#1 /usr/share/php/zend-framework-1.12.13/Zend/Http/Client.php(467): Zend_Http_Client->_validateHeaderValue('multipart/relat...')
#2 /usr/share/php/zend-framework-1.12.13/Zend/Http/Client.php(439): Zend_Http_Client->setHeaders('Content-Type', 'multipart/relat...')
#3 /usr/share/php/zend-framework-1.12.13/Zend/Gdata/App.php(650): Zend_Http_Client->setHeaders(Array)
#4 /usr/share/php/zend-framework-1.12.13/Zend/Gdata.php(219): Zend_Gdata_App->performHttpRequest('POST', 'http://uploads....', Array, Object(Zend_Gdata_MediaMimeStream), 'multipart/relat...', NULL)
#5 /usr/share/php/zend-framework-1.12.13/Zend/Gdata/App.php(908): Zend_Gdata->performHttpRequest('POST', 'http://uploads....',  in /usr/share/php/zend-framework-1.12.13/Zend/Http/Header/HeaderValue.php on line 124

Zend_Gdata_MediaMimeStream:L184

```public function getContentType()
    {
            return 'multipart/related;boundary="' .
             $this->_boundaryString . '"' . "\r\n";
     }
```

**Comment by froschdesign** [comment]
ping @weierophinney

**Comment by exilod** [comment]
Hope this gets fixed soon because now it's practically impossible to upload any file.

**Comment by platedodev** [comment]
no fix?
